name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Frontend Image
        run: |
          # Login to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # --- THE CHANGE IS HERE ---
          # We pull the secret from GitHub and pass it to the Docker build argument
          docker build \
            --build-arg VITE_API_URL="${{ secrets.VITE_API_URL }}" \
            -t asliadarsh/todo-frontend:${{ github.sha }} \
            -t asliadarsh/todo-frontend:latest \
            .

          docker push asliadarsh/todo-frontend:${{ github.sha }}
          docker push asliadarsh/todo-frontend:latest
